apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk080-llm-data-analyzer
  namespace: skala-practice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sk080-llm-data-analyzer
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: '/actuator/prometheus'
        update: eec80c1300c7c112f4a26fe39e4cb2d4
      labels:
        app: sk080-llm-data-analyzer
    spec:
      serviceAccountName: default
      imagePullSecrets:
        - name: sk080-secret
      containers:
      - name: llm-data-analyzer
        image: progamm3r/llm-data-analyzer:1.0.0
        imagePullPolicy: Always
        env:
        - name: USER_NAME
          value: sk080
        - name: NAMESPACE
          value: skala-practice
        - name: SPRING_PROFILES_ACTIVE  
          value: "prod"  
