apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: sk080-llm-data-analyzer-ingress
  namespace: skala-practice
spec:
  ingressClassName: public-nginx
  rules:
  - host: sk080-llm-data-analyzer.skala25a.project.skala-ai.com
    http:
      paths:
      - backend:
          service:
            name: sk080-llm-data-analyzer
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - 'sk080-llm-data-analyzer.skala25a.project.skala-ai.com'
    secretName: sk080-ingress-project-tls-cert
