apiVersion: v1
kind: Secret
metadata:
  name: sk080-llm-api-keys
  namespace: skala-practice
type: Opaque
stringData:
  OPENAI_API_KEY: "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"